/**
 * ESLint, flat config.
 *
 * `next build` does not run this (`next.config.mjs` sets `ignoreDuringBuilds`),
 * so lint is `npm run lint` and a lint failure is reported as a lint failure.
 *
 * ## What this file adds over `eslint-config-next`
 *
 * `02-architecture.md` §10 lists six import rules and ends with:
 *
 * > 6. Enforcement: an ESLint `no-restricted-imports` rule with per-module
 * >    patterns plus CI check for file length. **Both are wired in Phase 1.**
 *
 * So this file is the first of the two, and `scripts/check-file-length.mjs` is the
 * second. They are not redundant: ESLint reads a parsed import graph and can say
 * *which* import broke *which* rule, while the CI script reads the filesystem and
 * still works on a file ESLint cannot parse. A file that fails to parse is exactly
 * the file whose length nobody is watching.
 *
 * ## Why the restriction objects are composed rather than repeated
 *
 * `no-restricted-imports` is a single rule, and for any one file the **last**
 * config object that sets it wins outright — the lists are not merged. `jalali.ts`
 * is in `src/core/`, so it matches three scopes at once, and each needs a slightly
 * different list: it may import `date-fns-jalali` where nothing else may. Writing
 * three literal lists would mean three places to update when a boundary moves, and
 * the failure mode of forgetting one is silence. So the restriction *groups* are
 * named constants and each scope assembles its list from them.
 *
 * ## The clock rule
 *
 * `05-conventions.md` §8 is a binding constraint — "**No `new Date()` in business
 * logic.** Time comes from an injected clock, so that slot generation and
 * next-due computation are testable at any date" — and until now it was enforced
 * only by review. The selectors below are deliberately narrow: they match
 * `new Date()` with **no arguments** and `Date.now()`, which are the two ways to
 * read the ambient clock. `new Date(someValue)` is a parse, not a clock read, and
 * is left alone — a rule that flagged it would fire on legitimate boundary code
 * and be disabled within a week, which is worse than no rule.
 */

import next from 'eslint-config-next'
import tseslint from 'typescript-eslint'

/* ── Ignored paths ────────────────────────────────────────────────────────── */

/**
 * `clinic/` is the UI demo and the `.txt` / `.pdf` files beside it are the
 * specification: the product's **inputs**, tracked so that `docs/knowledge/` can be
 * traced back to them. They are read and never edited, so they are not linted.
 * `prisma/migrations/` is generated by Prisma and `src/generated/` by the Prisma
 * client generator; a generated file that lint rewrites is a generated file that no
 * longer matches its generator.
 */
const IGNORES = [
  'node_modules/**',
  '.next/**',
  'out/**',
  'build/**',
  'dist/**',
  'coverage/**',
  'next-env.d.ts',
  'playwright-report/**',
  'test-results/**',
  'blob-report/**',
  'clinic/**',
  'prisma/migrations/**',
  'src/generated/**',
]

/* ── The restriction groups ───────────────────────────────────────────────── */

/**
 * §10 rule 1, from every file: a module is reachable through its barrel and
 * nothing else.
 *
 * `@/modules/*​/*` matches one segment below a module — `@/modules/debts/lib/x` —
 * and `@/modules/*​/*​/**` matches deeper. The relative forms are listed too,
 * because `../../modules/debts/lib/x` reaches the same file through the same hole
 * and a rule that only understood the alias would be trivially bypassed.
 */
const BARREL_ONLY = {
  group: ['@/modules/*/*', '@/modules/*/*/**', '**/modules/*/*', '**/modules/*/*/**'],
  message:
    'Import a module through its barrel: `@/modules/<module>`. A path inside a module is a deep import, and a module is only responsible for its own barrel. (docs/knowledge/02-architecture.md §10 rule 1)',
}

/**
 * §10 rule 3: "`core` may not import from `modules`."
 *
 * The rule exists so that `core` stays a library — the worker, the web tier and
 * every module depend on it, so if it depended on a module the two would have to be
 * released together and the dependency would be a cycle. The direction is one-way
 * and this is the half of it that lint can see.
 */
const CORE_STAYS_BELOW_MODULES = {
  group: ['@/modules/*', '@/modules/*/**', '**/modules/*', '**/modules/*/**'],
  message:
    '`core` must not import from `modules`. The dependency runs one way: modules import core, never the reverse. (docs/knowledge/02-architecture.md §10 rule 3)',
}

/**
 * `01-tech-stack.md` §8.6 and `07-localization.md` §6.1: the calendar conversion
 * comes from `date-fns-jalali`, and **everything about how a value is displayed is
 * ours**. `jalali.ts` is the single file that bridges the two.
 *
 * A module that imports the library directly has bypassed the display layer, the
 * digit conversion and the bidi rules in one step — a date rendered straight from
 * the library is a Gregorian-looking or Latin-digited date, and neither is a
 * compile error. The subpath pattern is included because `date-fns-jalali/format`
 * is the same bypass with a longer specifier.
 */
const DATE_LIBRARY_IS_BEHIND_THE_BRIDGE = {
  group: ['date-fns-jalali', 'date-fns-jalali/**'],
  message:
    'Import the calendar through `@/core/localization`. `jalali.ts` is the only file that talks to `date-fns-jalali`, so that the display layer, the Persian digits and the RTL rules cannot be bypassed. (docs/knowledge/07-localization.md §6.1)',
}

/**
 * `05-conventions.md` §17: "**No component imports `@radix-ui/*` or `cmdk`
 * directly.** They are wrapped in `src/core/components/**` and reachable only
 * through that wrapper, so the token styling and the Persian-aware filter cannot
 * be bypassed."
 *
 * Radix supplies focus trapping, focus restoration, escape handling and `aria-*`
 * wiring; cmdk supplies the filtering model and the combobox keyboard interaction.
 * Neither supplies appearance, and the wrapper is what supplies it — along with
 * the Persian labels, the RTL behaviour, and cmdk's Persian-aware filter, which
 * `01-tech-stack.md` §8.4 says no caller may supply for itself. A direct import
 * bypasses all four at once and compiles cleanly.
 */
const HEADLESS_PRIMITIVES_ARE_BEHIND_THE_WRAPPER = {
  group: ['@radix-ui/*', '@radix-ui/*/**', 'cmdk', 'cmdk/**'],
  message:
    'Radix primitives and cmdk are wrapped in `src/core/components/**`. Import the wrapper, which owns the token styling, the Persian labels, the RTL behaviour and the Persian-aware filter. (docs/knowledge/05-conventions.md §17)',
}

/**
 * `01-tech-stack.md` §8.2: "**A Lucide icon imported directly into a component is
 * a finding** — it would carry the default stroke and break the icon language in a
 * way that is visible but easy to miss in review."
 *
 * Lucide's default stroke width is 2; the design system requires 1.7
 * (`08-ui-design-system.md` §42 and rule A7), and the whole point of pinning it is
 * that a wrong stroke width is not a compile error. The wrapper also applies the
 * RTL mirroring §42 requires for direction icons, and exposes no `fill` or colour
 * override — the three things §8.2 lists as the wrapper's obligations.
 */
const LUCIDE_IS_BEHIND_THE_WRAPPER = {
  group: ['lucide-react', 'lucide-react/**'],
  message:
    'Import icons through `@/core/components/icons`. A direct Lucide import carries Lucide’s default stroke width of 2 instead of the design system’s 1.7, and skips the RTL mirroring the wrapper applies. (docs/knowledge/01-tech-stack.md §8.2, docs/knowledge/08-ui-design-system.md §42)',
}

/**
 * The stack is CSS Modules over a CSS-variable token block
 * (`01-tech-stack.md` §1, `05-conventions.md` §9, `08-ui-design-system.md` §B), and
 * every component is built from the design system — "**No component library
 * theme**" is one of Phase 1's rules.
 *
 * The list is here so that re-introducing one is a lint error with a citation
 * rather than a `package.json` entry nobody notices. Adding one requires an ADR,
 * which is why the message says so.
 */
const NO_COMPONENT_LIBRARY = {
  group: [
    '@mui/*',
    '@material-ui/*',
    '@chakra-ui/*',
    '@mantine/*',
    '@radix-ui/themes',
    'antd',
    '@ant-design/*',
    'styled-components',
    '@emotion/*',
    '@stitches/*',
    'tailwindcss',
    'bootstrap',
    'react-bootstrap',
    'shadcn-ui',
    'class-variance-authority',
  ],
  message:
    'The stack is CSS Modules over the CSS-variable token block in `src/app/globals.css`; every component is built from the design system. Adding a component library or Tailwind requires an ADR. (docs/knowledge/01-tech-stack.md §1, docs/knowledge/08-ui-design-system.md preamble)',
}

/**
 * The two ways to read the ambient clock, and nothing else.
 *
 * `[arguments.length=0]` is what keeps this narrow: `new Date(row.scheduledAt)` is
 * a parse of a stored value and is allowed; `new Date()` is a read of the wall
 * clock and is not. See the file header for why the distinction is worth making.
 */
export const NO_AMBIENT_CLOCK = [
  {
    selector: 'NewExpression[callee.name="Date"][arguments.length=0]',
    message:
      '`new Date()` reads the ambient clock, which makes the code untestable at any date other than today. Take the time as a parameter, or from the injected clock. (docs/knowledge/05-conventions.md §8)',
  },
  {
    selector: 'CallExpression[callee.object.name="Date"][callee.property.name="now"]',
    message:
      '`Date.now()` reads the ambient clock, which makes the code untestable at any date other than today. Take the time as a parameter, or from the injected clock. (docs/knowledge/05-conventions.md §8)',
  },
]

/* ── Localization, in a file that renders ─────────────────────────────────── */

/**
 * A Persian string literal outside the catalog.
 *
 * One of Phase 1's rules is "**No Persian string literal in a component** — use
 * the catalog", and `05-conventions.md` §14 makes it a finding. The selector is
 * exact rather than lexical: it matches a **string or template literal whose value
 * contains a Persian character** and a **JSX text node** that does, so a Persian
 * word in a comment is not a violation (there are many, and they are the codebase's
 * citation style) while a Persian word in a `title=` attribute is.
 *
 * `U+0600–U+06FF` is the Arabic block, which is where Persian's letters live; ZWNJ
 * (U+200C) is included because a label is as likely to lose its joiner as to lose a
 * letter, and a check that only looked for letters would pass on a string that had
 * been stripped of every ZWNJ.
 */
export const NO_PERSIAN_LITERAL = [
  {
    selector: 'Literal[value=/[\\u0600-\\u06FF\\u200c]/]',
    message:
      'Persian text belongs in the catalog, not in a component. Move it to the module catalog (or `src/app/catalog.ts`) and import it. (docs/knowledge/05-conventions.md §14, docs/knowledge/07-localization.md §7.2)',
  },
  {
    selector: 'TemplateElement[value.raw=/[\\u0600-\\u06FF\\u200c]/]',
    message:
      'Persian text belongs in the catalog, not in a component — including inside a template literal. Move it to the catalog and import it. (docs/knowledge/07-localization.md §7.2)',
  },
  {
    selector: 'JSXText[value=/[\\u0600-\\u06FF\\u200c]/]',
    message:
      'Persian text belongs in the catalog, not in JSX. Move it to the catalog and import it. (docs/knowledge/07-localization.md §7.2)',
  },
]

/**
 * Formatting done inline, in a file that renders.
 *
 * `07-localization.md` §7.1 is explicit: "No component formats a value inline.
 * `new Intl.NumberFormat(...)` in a component is a finding — it belongs in this
 * module, where it is tested once." The three selectors are the three ways that
 * happens: constructing an `Intl` formatter, calling one without `new`, and the
 * `toLocale*` family.
 *
 * `toLocale*` is the more insidious of the three. It reads the **runtime's**
 * locale, so the same call renders Persian digits on a machine configured for
 * `fa-IR` and Latin digits on a CI runner configured for `en-US` — the exact
 * regression §9's "no Latin digits in any rendered surface" exists to catch, and
 * one that no unit test on a developer's laptop would ever see.
 */
export const NO_INLINE_LOCALIZATION = [
  {
    selector: 'NewExpression[callee.object.name="Intl"]',
    message:
      'An `Intl` formatter in a rendering file is a finding. Use `@/core/localization` — `formatNumber`, `formatDate`, `formatMoney` — where it is written once and tested at 100%. (docs/knowledge/07-localization.md §7.1)',
  },
  {
    selector: 'CallExpression[callee.object.name="Intl"]',
    message:
      'An `Intl` formatter in a rendering file is a finding. Use `@/core/localization`. (docs/knowledge/07-localization.md §7.1)',
  },
  {
    selector: 'CallExpression[callee.property.name=/^toLocale/]',
    message:
      '`toLocale*` formats against the runtime locale, which is not the product locale — it renders Latin digits on a machine that is not set to `fa-IR`. Use `@/core/localization`. (docs/knowledge/07-localization.md §4.1, §7.1)',
  },
]

/* ── The localization scope, exported for `scripts/check-i18n.mjs` ───────── */

/** The files that render: everything in `src/` except the tests. */
export const RENDER_FILES = ['src/**/*.ts', 'src/**/*.tsx']

/** Where a Persian literal, or an inline formatter, is allowed to be. */
export const RENDER_IGNORES = [
  /**
   * The layer that *defines* the catalog and the formatters: Persian lives there
   * on purpose (the locale data, the numbering, the bidi isolates), and so does
   * `Intl` — it is the tested-once implementation the rule points other files at.
   */
  'src/core/localization/**',
  /** Slugs and set members only; the labels are in the catalog. */
  'src/core/constants/**',
  /** Where the literals are allowed to be. */
  'src/app/catalog.ts',
  'src/modules/*/catalog.ts',
  'src/modules/*/catalog/**',
  /** A test may assert against a literal, and a fixture is not a surface. */
  'src/**/tests/**',
  'src/**/*.test.ts',
  'src/**/*.test.tsx',
]

/**
 * Every localization selector in one list, for `scripts/check-i18n.mjs`.
 *
 * The script runs these same selectors against the same files so that
 * `npm run check:i18n` fails on exactly the violations `npm run lint` fails on —
 * one definition, two entry points. `check:i18n` exists as a separate command
 * because a localization regression should be reported as a localization failure,
 * with the §-citations, rather than as one line among a hundred lint messages.
 */
export const LOCALIZATION_SELECTORS = [
  ...NO_AMBIENT_CLOCK,
  ...NO_PERSIAN_LITERAL,
  ...NO_INLINE_LOCALIZATION,
]

/* ── The import scopes ────────────────────────────────────────────────────── */

/**
 * Every library ban, in one list.
 *
 * Each scope below is this list minus its exemptions, plus the boundary rules that
 * apply to it. Written this way, adding a banned library is one edit here rather
 * than five — and the failure mode of the alternative, five hand-written lists, is
 * that four of them get updated.
 */
const LIBRARY_BANS = [
  DATE_LIBRARY_IS_BEHIND_THE_BRIDGE,
  HEADLESS_PRIMITIVES_ARE_BEHIND_THE_WRAPPER,
  LUCIDE_IS_BEHIND_THE_WRAPPER,
  NO_COMPONENT_LIBRARY,
]

/** Every ban except the named ones. See `LIBRARY_BANS`. */
const bansExcept = (...exempt) => LIBRARY_BANS.filter((ban) => !exempt.includes(ban))

/**
 * The directories that wrap a headless primitive, each named for the component it
 * exports rather than for the package it imports.
 *
 * They are exempt from the Radix/cmdk ban and nothing else — a wrapper may import
 * the library it wraps, and may not import a second one, may not import icons
 * directly, and may not import a styled library. That narrowness is the point: an
 * exemption that also lifted the other bans would make the wrapper directory the
 * one place none of the rules apply.
 */
const HEADLESS_WRAPPER_DIRECTORIES = [
  'combobox',
  'dialog',
  'dropdown-menu',
  'popover',
  'tabs',
  'tooltip',
]

/** Those directories, as the two file patterns each of them needs. */
const HEADLESS_WRAPPER_FILES = HEADLESS_WRAPPER_DIRECTORIES.flatMap((name) => [
  `src/core/components/${name}/**/*.ts`,
  `src/core/components/${name}/**/*.tsx`,
])

/** Every TypeScript file in `src/`. The barrel rule and every library ban. */
const RESTRICTIONS_SRC = { patterns: [BARREL_ONLY, ...bansExcept()] }

/** `src/core/`, where the dependency direction is constrained as well. */
const RESTRICTIONS_CORE = { patterns: [CORE_STAYS_BELOW_MODULES, ...bansExcept()] }

/** `jalali.ts`: the one file that may import `date-fns-jalali`. */
const RESTRICTIONS_JALALI = {
  patterns: [CORE_STAYS_BELOW_MODULES, ...bansExcept(DATE_LIBRARY_IS_BEHIND_THE_BRIDGE)],
}

/** `src/core/components/icons/`: the one directory that may import Lucide. */
const RESTRICTIONS_ICONS = {
  patterns: [CORE_STAYS_BELOW_MODULES, ...bansExcept(LUCIDE_IS_BEHIND_THE_WRAPPER)],
}

/** The wrapper directories: the only files that may import Radix or cmdk. */
const RESTRICTIONS_HEADLESS = {
  patterns: [CORE_STAYS_BELOW_MODULES, ...bansExcept(HEADLESS_PRIMITIVES_ARE_BEHIND_THE_WRAPPER)],
}

/** One scope. Each below differs only in its file pattern and its list. */
const importScope = (name, files, restrictions) => ({
  name,
  files,
  rules: { 'no-restricted-imports': ['error', restrictions] },
})

/**
 * In this order, and the order is load-bearing.
 *
 * For any one file the **last** of these to match sets `no-restricted-imports`, so
 * the narrowest scope has to come last. `jalali.ts` is matched by `src`, by `core`
 * and by itself, and is the only file allowed to import the calendar library;
 * `src/core/components/icons/Icon.tsx` is matched by `src`, by `core`, by
 * `components` and by `icons`, and is one of the few files allowed to import
 * Lucide.
 */
const IMPORT_SCOPES = [
  importScope('clinic/boundaries/src', ['src/**/*.ts', 'src/**/*.tsx'], RESTRICTIONS_SRC),
  importScope('clinic/boundaries/core', ['src/core/**/*.ts', 'src/core/**/*.tsx'], RESTRICTIONS_CORE),
  importScope(
    'clinic/boundaries/headless-wrappers',
    HEADLESS_WRAPPER_FILES,
    RESTRICTIONS_HEADLESS,
  ),
  importScope(
    'clinic/boundaries/icons',
    ['src/core/components/icons/**/*.ts', 'src/core/components/icons/**/*.tsx'],
    RESTRICTIONS_ICONS,
  ),
  importScope(
    'clinic/boundaries/date-bridge',
    ['src/core/localization/jalali.ts'],
    RESTRICTIONS_JALALI,
  ),
]

/* ── The config ───────────────────────────────────────────────────────────── */

const CONFIG_OBJECTS = [
  /**
   * Global ignores. An object whose only key is `ignores` ignores paths for every
   * config after it, so it comes first.
   */
  { name: 'clinic/ignores', ignores: IGNORES },

  ...next,

  /** `typescript-eslint`'s recommended set, scoped to the files it is for. */
  ...tseslint.configs.recommended.map((config) => ({ ...config, files: ['**/*.ts', '**/*.tsx'] })),

  ...IMPORT_SCOPES,

  {
    name: 'clinic/rules',
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      /**
       * `02-architecture.md` §10 rule 4. The same limit is checked by
       * `scripts/check-file-length.mjs` and by the `PostToolUse` hook in
       * `.claude/settings.json`; this is the copy that runs in `npm run lint`.
       */
      'max-lines': ['error', { max: 1000 }],

      /** `05-conventions.md` §8, encoded. See the file header. */
      'no-restricted-syntax': ['error', ...NO_AMBIENT_CLOCK],

      /** Nothing in this codebase uses loose equality; keep it that way. */
      eqeqeq: ['error', 'always', { null: 'ignore' }],

      /**
       * An unused parameter is usually a signature that changed and a call site
       * that did not. The `_`-prefixed exemption is the convention for a parameter
       * a type requires but the body deliberately ignores.
       */
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'all',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },

  {
    /**
     * The localization rules, in the files that render.
     *
     * This block comes **after** `clinic/rules` because `no-restricted-syntax` is a
     * single rule and the last config to set it wins — so a file matching both
     * scopes gets this list and not the other. `NO_AMBIENT_CLOCK` is therefore
     * repeated here, by reference rather than by copy: omitting it would silently
     * switch the clock rule off in every file under `src/`, which is the whole
     * codebase it was written for.
     */
    name: 'clinic/i18n',
    files: RENDER_FILES,
    ignores: RENDER_IGNORES,
    rules: {
      'no-restricted-syntax': ['error', ...LOCALIZATION_SELECTORS],
    },
  },
]

/**
 * Named, because `import/no-anonymous-default-export` fires on an array literal
 * exported directly — and a config file that emits its own warning is a config
 * file someone will weaken to silence.
 */
const eslintConfig = CONFIG_OBJECTS

export default eslintConfig
